# Generated by Django 5.2.7 on 2025-11-18 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teknoymart', '0004_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], max_length=100),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_alerts', models.BooleanField(default=True)),
                ('message_notifications', models.BooleanField(default=True)),
                ('system_activity_updates', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], default='en', max_length=100)),
                ('time_format_24h', models.BooleanField(default=True)),
                ('homepage_view', models.CharField(choices=[('dashboard', 'Dashboard'), ('inbox', 'Inbox'), ('activity', 'Recent Activity')], default='dashboard', max_length=200)),
                ('dark_mode', models.BooleanField(default=False)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=100)),
                ('layout_density', models.CharField(choices=[('comfortable', 'Comfortable'), ('compact', 'Compact')], default='comfortable', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_profile_public', models.BooleanField(default=False)),
                ('show_activity_public', models.BooleanField(default=False)),
                ('allow_data_export', models.BooleanField(default=True)),
                ('allow_data_analysis', models.BooleanField(default=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('login_alerts_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
