# Generated by Django 5.2.7 on 2025-12-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teknoymart', '0010_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('GCASH', 'GCash'), ('MAYA', 'Maya'), ('PAYPAL', 'PayPal'), ('COD', 'Cash On Delivery')], max_length=20),
        ),
    ]
