from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model 

class UserRecord(models.Model):
    id = models.UUIDField(primary_key=True, editable=False)   # generated by DB default gen_random_uuid()
    email = models.EmailField(unique=True)
    first_name = models.TextField()
    last_name = models.TextField()
    student_id = models.TextField(unique=True)
    course = models.TextField()               # or CharField with choices if you prefer
    password_hash = models.TextField(null=True, blank=True)  # NEVER store plaintext
    created_at = models.DateTimeField()

    class Meta:
        db_table = "users"   # exact table name in Supabase
        managed = False      # don't let Django try to create/alter it

class Product(models.Model):
    CATEGORY_CHOICES = [
        ("apparel","Apparel"),
        ("gadgets","Gadgets"),
        ("supplies","School Supplies"),
        ("food","Food"),
        ("merch","Merch"),
        ("other","Other"),
    ]
    owner      = models.ForeignKey(User, on_delete=models.CASCADE, related_name="products")
    title      = models.CharField(max_length=120)
    price      = models.DecimalField(max_digits=10, decimal_places=2)
    category   = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default="other")
    description= models.TextField(blank=True)
    image      = models.ImageField(upload_to="products/", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
class Product(models.Model):
    CATEGORY_CHOICES = [
        ('Clothing', 'Clothing'),
        ('Electronics', 'Electronics'),
        ('Food', 'Food'),
        ('Accessories', 'Accessories'),
    ]

    title = models.CharField(max_length=255)
    category = models.CharField(max_length=100, choices=CATEGORY_CHOICES)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    image = models.ImageField(upload_to='products/', blank=True, null=True)
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)  # <-- make sure this exists

    def __str__(self):
        return self.title