from django.db import models

class UserRecord(models.Model):
    id = models.UUIDField(primary_key=True, editable=False)   # generated by DB default gen_random_uuid()
    email = models.EmailField(unique=True)
    first_name = models.TextField()
    last_name = models.TextField()
    student_id = models.TextField(unique=True)
    course = models.TextField()               # or CharField with choices if you prefer
    password_hash = models.TextField(null=True, blank=True)  # NEVER store plaintext
    created_at = models.DateTimeField()

    class Meta:
        db_table = "users"   # exact table name in Supabase
        managed = False      # don't let Django try to create/alter it
